### ISSUE TITLE
Bootstrapping: initial checklist

### ISSUE THREAD

**Issue by shlomi-noach** [github/freno#1]
Various initial TODOs

- [x] name
- [x] initial directory structure
- [x] CI/deployment (GitHub internal)
- [x] config #10
- [x] run as a service
- [x] HTTP, `/lb-check` #3 
- [x] Raft, leader
- [x] backend polling ; concurrency 
- [x] metrics
- [ ] system tests

**Comment by shlomi-noach** [comment]
Old issue. Closing.
